/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "Cyclk12.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_MOT.h"
#include "vin.h"
#include "vin_aliases.h"
#include "err.h"
#include "err_aliases.h"
#include "phase.h"
#include "phase_aliases.h"
#include "enable.h"
#include "enable_aliases.h"
#include "sleep.h"
#include "sleep_aliases.h"
#include "Bootloadable_1.h"
#include "fault.h"
#include "fault_aliases.h"
#include "ovc.h"
#include "ovc_aliases.h"
#include "ADC.h"
#include "isense.h"
#include "isense_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "reset.h"
#include "reset_aliases.h"
#include "error.h"
#include "error_aliases.h"
#include "A.h"
#include "A_aliases.h"
#include "B.h"
#include "B_aliases.h"
#include "direction.h"
#include "direction_aliases.h"
#include "step.h"
#include "step_aliases.h"
#include "QDEC.h"
#include "QDEC_PVT.h"
#include "rxISR.h"
#include "TX_SEND.h"
#include "pwmClk.h"
#include "stepISR.h"
#include "txISR.h"
#include "EEPROM.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "QDEC_isr.h"
#include "QDEC_Cnt16.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

