# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\code\cypress\bootloaders\cncboot.cydsn\cncboot.cyprj
# Date: Mon, 13 Mar 2017 13:50:29 GMT
#set_units -time ns
create_clock -name {Clock_1(FFB)} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/ff_div_8}]]
create_clock -name {UART_SCBCLK(FFB)} -period 2166.6666666666665 -waveform {0 1083.33333333333} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 17 33} [list]
create_generated_clock -name {UART_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 105 209} -nominal_period 2166.6666666666665 [list]


# Component constraints for D:\code\cypress\bootloaders\cncboot.cydsn\TopDesign\TopDesign.cysch
# Project: D:\code\cypress\bootloaders\cncboot.cydsn\cncboot.cyprj
# Date: Mon, 13 Mar 2017 13:50:27 GMT
